const projects = [
  {
    name: "Job & Me",
    pic: "jobandme.png",
    tools: ["html", "css", "react", "js"],
    github: "https://github.com/NRG-BUILDS/job-me-frontend",
    live: "https://jobandme.vercel.app/",
    type: "major",
    desc: "A two-sided mobile marketplace connecting clients with skilled service providers. Built with React (Vite), Job & Me streamlines how people discover, book, and manage artisan services — with action-based updates and a smooth, responsive experience.",
  },
  {
    name: "BriteVillas",
    pic: "britevillas.png",
    tools: ["react", "typescript", "tailwind", "nodeJS", "mongoDB"],
    github: "",
    live: "https://britevillas-v2.onrender.com/",
    type: "major",
    desc: "A full-stack real estate platform for browsing and listing properties. Built with Node.js, Express, TypeScript, and React, BriteVillas features Google Maps integration, transactional email, and SPA-optimised analytics — deployed on Render with MongoDB Atlas.",
  },
  {
    name: "Movieroom",
    pic: "movieroomReact.png",
    tools: ["html", "css", "react", "js"],
    github: "https://github.com/NRG-BUILDS/movieroom",
    live: "https://nrg-movierooom.netlify.app",
    type: "major",
    desc: "An online app that fetches news, trending and other information about movies. Powered by TMDb API. Features include trending, popular, search, theme setting.",
  },
  {
    name: "Connect 4 Game",
    pic: "connect4game.jpg",
    tools: ["html", "tailwind", "react", "js"],
    github: "https://github.com/NRG-BUILDS/connect4game",
    live: "https://nrg-connect4game.netlify.app",
    type: "snippet",
    desc: "The popular game of connect 4. Players can choose names, select to play with friends or the computer and game progress is saved after each turn, so player can leave and come back anytime",
  },
  {
    name: "A Responsive News Page",
    pic: "news.jpg",
    tools: ["html", "tailwind", "js"],
    github: "https://github.com/NRG-BUILDS/news-page",
    live: "https://nrg-builds.github.io/news-page",
    type: "snippet",
    desc: "A modern and minimal online news page designed using tailwind. The use of CSS flexbox and grid makes it look beautiful on any screen size.",
  },
  {
    name: "Space Agency Site",
    pic: "space.webp",
    tools: ["tailwind", "react", "js", "framer motion"],
    github: "https://github.com/NRG-BUILDS/Space",
    live: "https://nrg-space.netlify.app",
    type: "snippet",
    desc: "A mini website that's out of this world. Check it out and be captivated by the nice transitions and animations made possible by Framer Motion",
  },
];

export default projects;
